spring.application.name=buddygoals-backend

# DATABASE CONFIG
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=
spring.jpa.properties.hibernate.dialect=
